spring:
  application:
    name: ms-audit
  profiles:
    active: develop
  cloud:
    config:
      fail-fast: true
  output:
    ansi:
      enabled: DETECT

spring.config.import: ${MS_CONF:configserver:http://ms-configserver:8080}

server:
  port: ${PORT:8080}