spring:
  application:
    name: ms-products
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cepardov/challenge
          search-paths: configurations
          default-label: develop
          clone-on-start: true
          skipSslValidation: true
  output:
    ansi:
      enabled: DETECT

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: info,health

logging:
  pattern:
    console: "%d{dd-MM-yy HH:mm:ss.S} [%-5level][%-35logger{35}]: %msg%n"
  level:
    ROOT: WARN
    com.globallogic: DEBUG