app: ms-products

spring:
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:develop-mariadb.infraestructure.svc.k0s.cepardov.cl}:3306/products_db
    username: application
    password: application2025
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect